name: triq ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    strategy:
      matrix:
        include:
          - image: erlang:24
          - image: erlang:25
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}
      options: "--entrypoint /bin/bash"

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: nomasystems/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run checks
        run: make ci-dialyze

      - name: Run tests
        run: make ci

      - name: Create test summary
        uses: test-summary/action@v1
        if: always()
        with:
          paths: '_build/test/logs/**/report.xml'
